users/urls.py
from django.urls import path
from users.views import *

app_name = 'posts'

urlpatterns = [
    path('', post, name="post_list"),
    path('<int:pk>/', PostDetailView, name='post_detail'),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post-update"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from io import BytesIO
from django.core.files import File


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=10, null=True)
    image = models.ImageField(default='default.png', upload_to="profile_img",)
    bio = models.TextField(max_length=300, null=True, blank=True)
    cover = models.ImageField(default='background.jpg',upload_to="cover_img",)

    def __str__(self):
        return self.user.username
    

class Category(models.Model):
    name = models.TextField(max_length=200)
    slug = models.SlugField(max_length=40)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


YEAR_CHOICES = [
    ('2550', '2550'),
    ('2551', '2551'),
    ('2552', '2552'),
    ('2553', '2553'),
    ('2554', '2554'),
    ('2555', '2555'),
    ('2556', '2556'),
    ('2557', '2557'),
    ('2558', '2558'),
    ('2559', '2559'),
    ('2560', '2560'),
    ('2561', '2561'),
    ('2562', '2562'),
    ('2563', '2563'),
    ('2564', '2564'),
]

class Project(models.Model):
    p_name = models.TextField(max_length=500)
    p_author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    p_date = models.CharField(
        max_length = 20,
        choices = YEAR_CHOICES,
        )
    p_type = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, related_name='categories' )
    p_abstract = models.TextField(max_length=2000)
    p_img = models.ImageField(null=True, blank=True)
    f_pdf = models.FileField(upload_to='pdfs/', null=True, blank=True)
    date_add = models.DateTimeField(auto_now_add=True)
    count_download = models.IntegerField(default=0, verbose_name=('count download'),null=True,blank=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.forms import fields
from users.models import Category,Project,Profile
from django.core.validators import RegexValidator


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(label='Full_name',)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.")
    last_name = forms.CharField(label='Phone',validators=[phone_regex], max_length=10)

    class Meta:
        model = User
        fields = ['username', 'first_name','email','last_name','password1', 'password2']


class categoryForm(forms.ModelForm):
    name = forms.CharField(label='Category Label',widget=forms.Textarea(attrs={'rows':2}))

    class Meta:
        model = Category
        fields = ('name',)

YEAR_CHOICES = [
    ('2550', '2550'),
    ('2551', '2551'),
    ('2552', '2552'),
    ('2553', '2553'),
    ('2554', '2554'),
    ('2555', '2555'),
    ('2556', '2556'),
    ('2557', '2557'),
    ('2558', '2558'),
    ('2559', '2559'),
    ('2560', '2560'),
    ('2561', '2561'),
    ('2562', '2562'),
    ('2563', '2563'),
    ('2564', '2564'),
]

class ProjectForm(forms.ModelForm):
    p_name = forms.CharField(label='',widget=forms.Textarea(attrs={'placeholder':'Add a Catchy Title','rows':1}))
    p_abstract = forms.CharField(label='',widget=forms.Textarea(attrs={'placeholder':'Start writing your post here.','rows':8}))
    p_type = forms.ModelChoiceField(label='Categories',queryset=Category.objects.all(), required=False)
    p_date = forms.ChoiceField(
        label= 'year',
        choices = YEAR_CHOICES,
        )
    f_pdf = forms.FileField(label='Add a file')

    class Meta:
        model = Project
        fields = ('p_name','p_abstract', 'p_type','p_date', 'p_img','f_pdf')

users/views.py
from typing import List
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,UpdateView,DeleteView
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from systems.models import * 
from users.forms import categoryForm,ProjectForm,UserRegisterForm
from users.models import Category,Profile,Project
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')
            return redirect('login')

    else:
        form = UserRegisterForm()

    return render(request, 'users/register.htm', {'form':form})

def post (request):
    view_Project = Project.objects.all()
    u_user = User.objects.all()
    view_profile = Profile.objects.filter(user_id=request.user)
    
    context = {
        'view_Project':view_Project,
        'u_user':u_user,
        'view_profile':view_profile
    }
    return render(request, 'users/main/posts.htm', context)


def PostDetailView(request, pk):
    try:
        p = Project.objects.get(pk=pk)
    except Project.DoesNotExist:
        raise Http404("does not exist")

    if 'increment_download' in request.POST:
            increment = Project.objects.get(pk=pk)
            increment.count_download += 1
            increment.save()

    context = {'project': p}
    return render(request, 'users/main/assets/postdetail.htm', context)

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'users/main/assets/confirm_del.htm'
    success_url = reverse_lazy('posts:post_list')

    def get_object(self , *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Project.objects.get(pk=pk)
        if not obj.p_author.user == self.request.user:
            messages.warning(self.request, 'your need to be the author of the post in order to delete')
        return obj
    

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProjectForm
    model = Project
    template_name = 'users/main/assets/update.htm'
    success_url = reverse_lazy('posts:post_list')

    def form_valid(self,form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.p_author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None,"You need to be the author of the post in order to update it")
            return super().form_invalid(form)

class settingUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = 'users/main/updateProfile.htm'
    fields = ['full_name','phone','image','cover']
    
    def get_success_url(self): 
        return reverse('profiles:profile_default', args=[str(self.request.user.id)])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_profile'] = Profile.objects.filter(user_id=self.request.user)
        return context


def setting (request):
    view_profile = Profile.objects.filter(user_id=request.user)

    context = {
        'view_profile':view_profile
    }

    return render(request, 'users/main/setting.htm',context)

def createPost (request):
    create_category = categoryForm()
    p_post = ProjectForm()
    view_category = Category.objects.all()
    view_profile = Profile.objects.filter(user_id=request.user)
    
    if 'submit_c_category' in request.POST:
        create_category = categoryForm(request.POST)
        if create_category.is_valid():
            instance = create_category.save(commit=False)
            instance.save()
            create_category = categoryForm()

    if 'submit_p_post' in request.POST:
        p_post = ProjectForm(request.POST, request.FILES)
        if p_post.is_valid():
            instance = p_post.save(commit=False)
            instance.p_author = Profile.objects.get(user=request.user)
            instance.p_type = Category.objects.get(id=request.POST.get('p_type'))
            instance.save()
            p_post = ProjectForm()
            return redirect('posts:post_list')

    context = {
        'create_category' : create_category,
        'view_category' : view_category,
        'p_post':p_post,
        'view_profile':view_profile
    }
    return render(request, 'users/main/assets/createpost.htm', context)

@login_required
# def profile(request):
#     view_profile = Profile.objects.filter(user_id=request.user)

#     context = {
#         'view_profile':view_profile
#     }
#     return render(request, 'users/main/profile_.htm',context)

def p_profile(request):
    view_profile = Profile.objects.filter(user_id=request.user)

    context = {
        'view_profile':view_profile
    }
    return render(request, 'users/main/profile_.htm',context)

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = 'users/main/profile_.htm'
    fields = ['bio']

    def get_success_url(self): 
        return reverse('profiles:profile_default', args=[str(self.request.user.id)])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['view_profile'] = Profile.objects.filter(user_id=self.request.user)
        return context

users/templates/users/main/assets/confirm_del.htm
{% extends 'base.html' %}

{% block title %}
    delete post
{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class="messages">
                    <div class="harder">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="container">
        <div class="mt-5 mb-5">
    {% if not messages %}
        <div class="card p-5">
            <h3>Delete Post?</h3>
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete post?</p>
                <button type="submit" class="btn btn-danger">Yes</button>
                <a href="{% url 'posts:post_list'%}" class="btn btn-secondary">cancel</a>
            </form>
        </div>
    {% endif %}
</div>
</div>
{% endblock content %}

users/templates/users/main/assets/createpost.htm
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<link href="{% static 'assets/createpost.css'%}" rel="stylesheet" />
{% for view_p in view_profile %}
<div class="container p-5">
  <div class="card pading">
    <div class="row">
      <div class="col-6">
          <div class="row">
              <div class="col-1"><img src="{% static 'img/default.png' %}" height="30px" ></div>
              <div class="col-11"><p class="h6 pt-1">{{view_p.full_name}}</p></div>
          </div>
        </div>
      <div class="col-6 text-right">
        <button
          type="button"
          class="btn btn-light"
          data-toggle="modal" 
          data-target="#exampleModalCenter"
        >
          Post Settings
        </button>
      </div>
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Post Setting</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active" id="category-tab" data-toggle="tab" href="#category" role="tab" aria-controls="category" aria-selected="true">Categories</a>
                    </li>
                  </ul>
                  <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="category" role="tabpanel" aria-labelledby="category-tab">
                        <div class="choose pt-4 pb-5">
                        <p class="h6">Choose a category</p>
                        
                        <div class="row">
                            {% for view_category in view_category %}
                            <div class="col-4">
                                <div class="card p-2 text-center">
                                {{view_category.name}}
                            </div>
                        </div>
                        {% endfor %}
                        </div>
                        
                    </div>
                    <hr/>
                    <form action="" method="POST" enctype="multipart/form-data" class="pt-4">
                        {% csrf_token %} {{create_category|crispy}}
                        <div class="text-center">
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" name="submit_c_category" >Save changes</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>
    <form action="" method="POST" enctype="multipart/form-data" class="pt-4">
        {% csrf_token %} {{p_post|crispy}}
        <div class="text-center">
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary" name="submit_p_post" >Save changes</button>
          </div>
        </div>
      </form>
  </div>
</div>
{% endfor %}
{% endblock content %}

users/templates/users/main/assets/postdetail.htm
{% extends 'base.html' %} {% load static %} {% block title %} Blog {{project.id}}
{% endblock title %} {% block content %}
<div class="container">
  <div class="card p-4 mb-4 mt-4 m-5 p-5">
    <div class="card-body">
      <div class="card-title pb-2">
        <div class="row pb-2">
          <div class="col-1">
            <img src="{% static 'img/default.png' %}" height="45px" />
          </div>
          <div class="col-11 mt-2">
            <div class="row">
              <div class="col-5">
                {{project.p_author}} | {{project.date_add}}
              </div>
              <div class="col-7">
                {% if 'admin' == user.username %}
                <div class="float-right">
                <a
                  class="btn btn-secondary btn-sm"
                  href="{% url 'posts:post-update' project.id %}"
                  >Update</a
                >
                <a
                  class="btn btn-danger btn-sm"
                  href="{% url 'posts:post-delete' project.id %}"
                  >Delete</a
                >
              </div>
              {% else %}

              {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <h3 class="card-title pb-4">{{project.p_name}}</h3>
      {% if project.p_img %}
      <img
        class="card-img-top mb-4"
        src="{{ project.p_img.url }}"
        width="100%"
      />
      {% endif %}
      <p class="card-text pb-3">{{project.p_abstract}}</p>
      <hr />
      {% if user.is_authenticated %}
      <form action="" method="post">
        {% csrf_token %}
      <a href="{{project.f_pdf.url}}" class="btn btn-light" id="link" download hidden></a>
      <button class="btn btn-light" name="increment_download"  onclick="document.getElementById('link').click()">DOWNLOAD PDF</button>
      </form>
      {% else %} Can't download PDF file.<a href="{% url 'login' %}">
        You must login/register</a
      >
      {% endif %}
      <hr />
      <p class="card-text pb-3">0 views write a comment</p>
    </div>
  </div>
</div>

<!-- <script>
  function downloaD(url,name) {
    fetch(url).then(async(res) => {
      const dfile = await res.blob();
      var blobURL = 
    })
  }
</script> -->
{% endblock content %}

users/templates/users/main/assets/update.htm
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    update post
{% endblock title %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="card p-5">
        <h3>Update Post</h3>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-primary mt-5">Update</button>
        </form>
    </div>
</div>
{% endblock content %}