systems/urls.py
from os import name
from django.urls import path
from users.views import *

app_name = 'profiles'

urlpatterns = [
    path('', p_profile, name="profile_def"),
    path('<int:pk>', ProfileUpdateView.as_view() ,name="profile_default"),
    path('settings/<int:pk>', settingUpdateView.as_view(),name="settings")
]

users/urls.py
from django.urls import path
from users.views import *

app_name = 'posts'

urlpatterns = [
    path('', post, name="post_list"),
    path('<int:pk>/', PostDetailView, name='post_detail'),
    path('<pk>/delete/', PostDeleteView.as_view(), name="post-delete"),
    path('<pk>/update/', PostUpdateView.as_view(), name="post-update"),
]

templates/main/about.html
{% extends 'base.html' %} {% load static %}
{% block title %} About {% endblock title %}
 {% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="container pb-5">
  <div class="OUR-faculty-of-it">
    <p class="font-size text-center">OUR faculty of IT</p>
    <p class="h5 w-50 center text-center">
      Faculty of Information Technology Eastern Asia University There are 2 types of learning styles, 
      normal and special, and you can contact the administrator. or contact via this information.
    </p>
  </div>

  <div class="values">
    <div class="row pb-5">
      <div class="col-6 position-img">
        <img class="img" src="{% static 'img/itcongrat.webp' %}" >
      </div>

      <div class="col-6">
        <div class="Principal w-75">
          <p class="h3">Faculty vision</p>
          <p class="h5">
            <br>
            learning agency information technology
    <br><br>

    Aiming to produce IT graduates for the ASEAN job market
          </p>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-6">
        <div class="vision w-50">
          <p class="h3 pb-3">Faculty resolutions</p>
          <p class="h5">
            <br>
            Committed to managing education
    <br><br>

    Create IT innovations,with quality and virtue
          </p>
          <!--<ul>
            <li>Be Kind</li>
            <li>Be Respectful</li>
            <li>Be Responsible</li>
            <li>Honest</li>
          </ul> -->
        </div>
      </div>
      <div class="col-6 pr-5">
        <div class="position-img2">
         <img class="img" src="{% static 'img/student.it1.jpg' %}" ></div>
        </div>
    </div>
  </div>


  <div class="staff">
    <p class="font-size text-center">IT STAFF DIRECTORY</p>
    <p class="h5 w-50 center text-center">
      Directory of personnel or staff of the Faculty of IT, as information for personal contact.
    </p>
  </div>
  <br>
  <div class="container">
    <div class="row pb-5">
      <div class="col center text-center">
        <p class="h2 pb-2">Dr.Kannicha</p>
        <p class="h4 pb-4">(Dean,Faculty of Information Technology)</p>
        <p class="h5 pb-1">Kannicha@eau.ac.th</p>
      </div>
    </div>
<br>
    <div class="row pb-5">
      <div class="col text-center">
        <p class="h2 pb-2">Mrs.Sukhonthip</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Sukhontip@eau.ac.th</p>
      </div>
      <div class="col text-center">
        <p class="h2 pb-2">Dr.Sukontip</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Sukontip@eau.ac.th</p>
      </div>
      <div class="col text-center">
        <p class="h2 pb-2">Mrs.Areeya</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Areeya@eau.ac.th</p>
      </div>
      </div>
    </div>
<br>
    <div class="row pb-5">
      <div class="col text-center">
        <p class="h2 pb-2">Mr.Sorawit</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Sorawit@eau.ac.th</p>
      </div>
      <div class="col text-center">
        <p class="h2 pb-2">Mr.Nikorn</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Nikorn@eau.ac.th</p>
      </div>
      <div class="col text-center">
        <p class="h2 pb-2">Mr.Thatchakon</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Topsapon@eau.ac.th</p>
      </div>
      </div>
    </div>
<br>
  </div>
  <div class="container">
    <div class="row pb-5">
      <div class="col center text-center">
        <p class="h2 pb-2">Mrs.Supranee</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Supraneev@eau.ac.th</p>
      </div>
      <div class="col center text-center">
        <p class="h2 pb-2">Dr.Suwannee</p>
        <p class="h4 pb-4">(Lecturer,Faculty of IT)</p>
        <p class="h5 pb-1">Suwannee@eau.ac.th</p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/main/academics.html
{% extends 'base.html' %} {% load static %}
{% block title %} ACADEMICS {% endblock title %}
 {% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="container pb-5">
  <div class="OUR-faculty-of-it">
    <p class="font-size text-center">ACADEMICS</p>
    <p class="h6 w-50 center text-center">
      I'm a paragraph. Click here to add your own text and edit me. It’s easy.
      Just click “Edit Text” or double click me to add your own content and make
      changes to the font.
    </p>
  </div>

  <div class="values">
    <div class="row pb-5">
      <div class="col-6"></div>

      <div class="col-6">
        <div class="Principal w-75">
          <p class="h3">Principal's Message</p>
          <p class="h6">
            I'm a paragraph. Click here to add your own text and edit me. It’s
            easy. Just click “Edit Text” or double click me to add your own
            content and make changes to the font.
          </p>
          <p class="h6">
            I'm a paragraph. Click here to add your own text and edit me. It’s
            easy. Just click “Edit Text” or double click me to add your own
            content and make changes to the font.
          </p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-6">
        <div class="vision w-50">
          <p class="h3 pb-3">Vision & Values</p>
          <ul>
            <li>Be Kind</li>
            <li>Be Respectful</li>
            <li>Be Responsible</li>
            <li>Work Hard</li>
            <li>Have Fun</li>
          </ul>
        </div>
      </div>
      <div class="col-6"></div>
    </div>
  </div>
</div>
{% endblock content %}

templates/main/administrator.html
{% extends 'base.html' %} {% load static %}
{% block title %} Administrator {% endblock title %}
 {% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="container pb-5">
  <div class="OUR-faculty-of-it">
    <p class="font-size text-center">administrator</p>
    <p class="h6 w-50 center text-center">
      Administrators must log in. To manage project information by adding, deleting, editing, etc.
    </p>
  </div>

<div class="download">
    <p class="font-size">Top 5 BEST DOWNLOAD</p>
</div>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Rating</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
  {% for rating_download in best_download %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{rating_download.p_name}}</td>
      <td>{{rating_download.p_author}}</td>
      <td>{{rating_download.count_download}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>


</div>
{% endblock content %}

templates/main/contact.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %}
{% block title %} Contact {% endblock title %}
 {% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="container pb-3">
  <div class="OUR-faculty-of-it">
    <p class="font-size text-center">CONTACT US</p>
    <p class="h4 w-50 center text-center">
      Contact or inquiry can be made 
      according to the needs 
      or interests of the user.
    </p>
  </div> 
  
  <div class="values">
    <!--<div class="row pb-5">
      <div class="col-6 position-img">
        <img class="position-img" src="{% static 'img/logo.png' %}" >
      </div>

      <div class="col-6">
        <div class="Principal w-75">
          <p class="h3">Principal's Message</p>
          <p class="h6">
            hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
            hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
            hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
          </p>
          <p class="h6">
            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
          </p>
        </div>
      </div>
    </div> -->

    <!-- <div class="row">
      <div class="col-6">
        <div class="vision w-50">
          <p class="h3 pb-3">Vision & Values</p>
          <ul>
            <li>jjjjjjjjjjjj</li>
            <li>kkkkkkkkkkkkkkkk</li>
            <li>lllllllll</li>
            <li>mmmmmmmmmmm</li>
            <li>nnnnnnnnnnn</li>
          </ul>
        </div>
      </div> -->
      <div class="row pb-5">
        <div class="col-6 position-img">
          <img class="img" src="{% static 'img/student.it1.jpg' %}" >
          <br><br><br><br>
          <img class="position-img" src="{% static 'img/contact.png' %}" >
        </div>
      <div class="col-6 contact-padding">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %} {{c_contact|crispy}}
          <div class="text-center">
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-primary" name="submit_c_contact" >Save changes</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/main/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'footer.css' %}" />
<div class="footer p-4">
   

  <div class="row">
    <div class="col-3">
        <a class="nav-link" href="{% url 'home' %}">
          <img src="{% static 'img/Logo.IT.png' %}" 
            width="180px" height="180px" align="left"/>  
        </a>
    </div>
    <div class="col-3 pt-4">
      <p class="h5 pb-3">QUICK NAVIGATION</p>
      <div class="row pb-2">
        <div class="col-5">About</div>
        <!--<div class="col-7">Admin</div>-->
      </div>
      <div class="row pb-2">
        <!--<div class="col-5">Academics</div>-->
        <div class="col-7">Contact</div>
      </div>
      <div class="row pb-2">
        <div class="col-5">Students</div>
        <div class="col-7"></div>
      </div>
    </div>
    <div class="col-3 pt-4">
      <p class="h5 pb-3">STAY CONNECTED</p>

      <div class="row pb-2">
        <div class="col-12">
         <a href="https://www.youtube.com/channel/UC7-Aqr0PSzR1zrySZ5wK4Ug">Vlog IT EAU</a>
        </div>
      </div>

      <div class="row pb-2">
        <div class="col-12">
          <a href="https://reg.eau.ac.th/registrar/home.asp">reg.eau.ac.th</a>
        </div>
      </div>

      <div class="row pb-2">
        <div class="col-12">
          <a href="https://www.eastern-asia.space/">EAU-Webpage</a>
        </div>
      </div>

    </div>
    <div class="col-3 pt-4">
      <p class="h5 pb-3">GET IN TOUCH</p>
      <div class="row pb-2">
        <div class="col-9">
          (IT) Eastern Asia University
          <br>
          N.200, V.1, R.Rangsit-Nakhon Nayok,
          D.Rangsit, A.Thanyaburi, P.Pathum Thani, CA.12110 
          <br>
          <p> Tel:  <a href="tel:025771028-31">025771028-31 per 302/387</a></p>
          <a href = "mailto: 61180003@stu.eau.ac.th">Send Email</a>
          
        </div>
      </div>
    </div>
  </div>
</div>
<div class="footer-bottom">
  <p class="h6 text-center pt-3">
    © 2021 by Faculty of Information Technology Eastern Asia University
  </p>
</div>

templates/main/home.html
{% extends 'base.html' %} {% load static %} {% block title %} Home {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'home.css' %}" />

<div class="hero">
  <div class="contant p-5">
    <p class="h1">Faculty of IT</p>
    <p class="h4 pt-2 pb-3">Welcome to IT Project Knowledge</p>
    <a href="{% url 'search' %}"
      ><button type="button" class="btn btn-danger">search project</button></a
    >
  </div>
</div>
<div class="middle"></div>

<div class="register_to_download">
  <div class="best pb-5">
    <p class="font-size text-center">BEST DOWNLOAD PROJECT</p>
  </div>
 
  <div class="card-deck">
    {% for p in best_download %}
    <div class="card">
      {% if p.p_img %}
      <a href="{% url 'posts:post_detail' p.id %}">
        <img class="card-img-top" src="{{ p.p_img.url }}" height="200px" />
      </a>
      {% else %}
      <div class="center text-center">ไม่มีรูป</div>
      {% endif %}
      <div class="card-body">
        <h6 class="card-title">
          <div class="row pb-2">
            <div class="col-3">
              <img src="{% static 'img/default.png' %}" height="45px" />
            </div>
            <div class="col">
              <div class="row">
                <div class="col h6">{{p.p_author}}</div>
              </div>
              <div class="row">
                <div class="col h6">{{p.p_date}}</div>
              </div>
            </div>
          </div>
        </h6>
        <a href="{% url 'posts:post_detail' p.id %}">
          <h3 class="card-title pb-2 h4">{{p.p_name}}</h3>
          <p class="card-text pb-3 h6">{{p.p_abstract}}</p>
        </a>  
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

templates/main/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'navbar.css' %}" />
<nav class="navbar navbar-expand-sm navbar-light bg-white main-nav">
  <div class="container justify-content-center p-0">
    <ul class="nav navbar-nav w-100 flex-nowrap">
       <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </ul>
    <ul class="nav navbar-nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">
          <img src="{% static 'img/Logo.IT.png' %}" width="95px" height="95px" align="center"/>
          
      </a>
      </li>
    </ul>
    <ul class="nav navbar-nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">
          
          <img src="{% static 'img/logo11.PNG' %}" width="160px" height="95px" align="center"/>
      </a>
      </li>
    </ul>
    <ul class="nav navbar-nav w-100 justify-content-end">
      <li class="nav-item">
        <span class="material-icons md-30"> notifications </span>
        <span></span>
         {% if user.is_authenticated %}
        <span class="dropdown">
          <div
            class="btn btn-default dropdown-toggle btn-dropdown"
            type="button"
            id="menu1"
            data-toggle="dropdown"
          >
            <img class="img_dropdown" src="{% static 'img/default.png' %}" />
            <span class="caret"></span>
          </div>
          <div class="dropdown-menu">
            {% if 'admin' == user.username %}
              <a class="dropdown-item" href="{% url 'profiles:profile_default' user.id %}">Profile</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'profiles:profile_default' user.id %}">Profile</a>
            {% endif %}
            {% if 'admin' == user.username %}
            <a class="dropdown-item" href="{% url 'posts:post_list' %}">Blog Posts</a>
            {% else %}
            {% endif %}
            {% if 'admin' == user.username %}
            <a class="dropdown-item" href="{% url 'profiles:settings' user.id %}">Settings</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'profiles:settings' user.id %}">Settings</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
          </div>
        </span>
        {% else %}
          <span class="btn btn-dropdown"><a href="{% url 'login' %}"> Login / register</a></span>
        {% endif %}
  <!--       <span id="cart-icon" class="material-icons pt-2 pl-3 md-30">
          facebook
        </span>
        <span class="pt-2 pl-3">
          <img class="img_size_30" src="{% static 'img/twitter.png' %}">
        </span>
        <span class="pt-2 pl-3">
          <img class="img_size_30" src="{% static 'img/instagram.png' %}">
        </span>
        <span class="pt-2 pl-3">
          <img class="img_size_30" src="{% static 'img/youtube.png' %}">
        </span> -->
      </li>
      <li class="nav-item"></li>
    </ul>
  </div>
</nav>
<nav class="navbar navbar-expand-lg navbar-dark bg-colors">
  <div class="container">
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbar10"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbar10">
      <div class="container">
        <ul class="navbar-nav nav-fill w-100">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'academics' %}">Academics</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'students' %}">Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          {% if user.is_authenticated %}
          {% if 'admin' == user.username %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'administrator' %}">Admin</a>
          </li>
          {% else %}
            
          {% endif %}
          {% else %}
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>

templates/main/search.html
{% extends 'base.html' %} {% load static %} {% block title %} Search {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'search.css' %}" />
<div class="container mt-5">
<div class="filter">
<form method="GET" action="{% url 'search' %}">
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="title" placeholder="หัวข้อ" />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>        
        </div>
        {% comment %} <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="author" placeholder="ชื่อผู้เขียน" />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>        
        </div> {% endcomment %}
        <div class="form-row">
          <div class="form-group col-md-4">
            <select id="category" class="form-control" name="category">
              <option selected>ปี</option>
              {% for v in v_project %}
              <option value="{{ v.p_date }}">{{ v.p_date }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <button type="submit"class="btn btn-primary">Search</button>
      </form>

  </div>
  </div>
{% if p_project %}
<div class="container">
  {% for p in p_project %}
  <div class="card p-4 mb-4 mt-4">
    <div class="row">
      <div class="col-4">
        {% if p.p_img %}
        <a href="{% url 'posts:post_detail' p.id %}">
          <img class="card-img-top" src="{{ p.p_img.url }}" width="100%" />
        </a>
        {% else %}
        <div class="center text-center">ไม่มีรูป</div>
        {% endif %}
      </div>
      <div class="col-8">
        <div class="card-body">
          <div class="card-title pb-2">
            <div class="row pb-2">
              <div class="col-1">
                <img src="{% static 'img/default.png' %}" height="45px" />
              </div>
              <div class="col-11">
                <div class="row">
                  <div class="col">{{p.p_author}}</div>
                </div>
                <div class="row">
                  <div class="col">{{p.p_date}}</div>
                </div>
              </div>
            </div>
          </div>
          <a href="{% url 'posts:post_detail' p.id %}">
            <h3 class="card-title pb-4">{{p.p_name}}</h3>
            <p class="card-text pb-3">{{p.p_abstract}}</p>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<div class="container">
  <div class="notFound">
    <div class="card text-center p-5">Not Found</div>
  </div>
</div>
{% endif %}
      
{% endblock %}

templates/main/students.html
{% extends 'base.html' %} {% load static %} {% block title %} Students {% endblock title %} {% block content %}
<link rel="stylesheet" href="{% static 'about.css' %}" />
<div class="container pb-5">
  <div class="OUR-faculty-of-it">
    <p class="font-size text-center">OUR STUDENTS</p>
    <p class="h4 w-50 center text-center">
      Students for the Faculty of IT 
      There will be various activities.
      and live as a family and 
      can easily consult with friends and seniors 
      and can consult with teachers easily.
    </p>
  </div>

  <div class="values">
    <div class="row pb-5">
      <div class="col-6 position-img">
        <img class="img" src="{% static 'img/waikru.jpg' %}" >
      </div>

      <div class="col-6 position-img">
        <img class="img" src="{% static 'img/3.1.jpg' %}" >
      </div>
    </div>

    <div class="row">
        <div class="col-6 position-img">
          <img class="img" src="{% static 'img/9.jpg' %}" >
        </div>

      <div class="col-6 position-img">
        <img class="img" src="{% static 'img/5.3.jpg' %}" >
      </div>
    </div>
  </div>
</div>
{% endblock content %}